export const defaultTrackerState = {
  tabs: ["Welcome", "Descendants", "Weapons", "Reactors", "Materials", "Farming", "Mastery", "Builds", "Friends"],
  activeTab: "Welcome",
  activities: [],
  weapons: [],
  reactors: [],
  materials: [],
  descendants: [],
  builds: [],
  goals: [],
  goalsFilters: { hideCompleted: false, onlyActive: false },
  weaponFilters: { search: "", rarity: "all", rounds: "all", sort: "name-asc", ownership: "all" },
  descFilters: { search: "", element: "all", ownership: "all" },
  buildFilters: { search: "", type: "all" },
  filters: { element: "all", skill: "all" },
  descFilter: "all",
  notesTabs: { Weapons: [] },
  sharePrivacy: "open" as const,
};
