services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: tfd_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4+P>P8."5|XoYy
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
